### ISSUE TITLE
Buildspec for AWS CodePipeline

### ISSUE THREAD

**Issue by impalah** [press-any-key-tech/tcp-dummy-services#7]
1. Sube tu archivo buildspec a un bucket de S3.
2. En la etapa de compilación de tu pipeline, selecciona "Insert build commands".
3. En "Build commands", selecciona "Switch to editor".
4. En el editor, introduce el siguiente código:

```
version: 0.2
phases:
  install:
    commands:
      - aws s3 cp s3://my-bucket/buildspec.yml . # reemplaza 'my-bucket' y 'buildspec.yml' con tu bucket y archivo
  pre_build:
    commands:
      - echo "Executing the commands in the buildspec file from S3"
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

```
